config/routes.rb
Rails.application.routes.draw do
  resources :albums
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :songs

  def songs_attributes=(songs)
    songs.each do |key, song|
      #byebug
      unless song['title'] == ''
        @song = self.songs.find_or_create_by(title: song['title'])
        @song.update(song)
      end
    end
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums
  has_many :songs, through: :albums
  has_many :genres, through: :songs
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :song_genres
  has_many :songs, through: :song_genres
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :song_genres
  has_many :genres, through: :song_genres
  belongs_to :artist

  def titleized_title
    self.title.titleize
  end

  def titleized_artist
    self.artist.name.titleize
  end

  def titleized_genres
    self.genres.pluck(:name).join(',').titleize
  end

  def artist_attributes=(artist)
    unless artist['name'] == ''
        self.artist = Artist.find_or_create_by(name: artist['name'].downcase)
    end
  end

  def genres_attributes=(genres)
    #byebug
    genres.each do |key, genre|
      unless genre['name'] == ''
          self.genres << Genre.find_or_create_by(name: genre['name'].downcase)
      end
    end
  end



end

app/models/song_genre.rb
class SongGenre < ActiveRecord::Base
  belongs_to :song 
  belongs_to :genre
end 

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums=Album.all
  end

  def new
    @album=Album.new
    @songs_attributes = Array.new(7) { @album.songs.build }
    @genres_attributes = Array.new(2) { Genre.new }
  end

  def create
    @album=Album.create(name: album_params['name'])
    @album.update(album_params)
    redirect_to album_path(@album)
  end

  def show
    @album=Album.find(params[:id])
  end

  private

  def album_params
    params.require(:album).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  end

  def new
    @artist=Artist.new
  end

  def create
    @artist=Artist.new(artist_params)
    byebug
  end

  def show
    @artist=Artist.find(params[:id])
  end

  private

  def artist_params
    params.require(:artist).permit(:name, album_attributes: [:name, song_attributes: [:title] ])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
  end

  def new
    @song=Song.new
    @album = @song.albums.build
    @artist = @album.artist.build
  end

  def create
    byebug
    @song=Song.new(song_params)
  end

  def show
    @song=Song.find(params[:id])
  end

  private

  def song_params
    params.require(:song).permit(:title, album_attributes: [:name, artist_attributes: [:name] ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<% @albums.each do |album| %>
  <h2><%= link_to album.name, album_path(album) %></h2>
<% end %>

app/views/albums/new.html.erb
<%= form_for @album do |f| %>
  
  Album name: <%= f.text_field :name %><br>
  <hr><br>
  <!--
  Songs in album: <input type="number" id="songCount" min="1" max="30"><br><br>
  -->
  <div id="songInputs">
    <%= f.fields_for :songs, @songs_attributes do |songs| %>
      Title: <%= songs.text_field :title %> 
      <%= songs.fields_for :artist, Artist.new do |a| %>
        Artist: <%= a.text_field :name %>
      <% end %> 
      Genres: 
      <%= songs.fields_for :genres, @genres_attributes do |g| %>
        <%= g.text_field :name %>
      <% end %>
      <br>
    <% end %>
  </div>

  <%= f.submit %>
<% end %>  

app/views/albums/show.html.erb
<h1>Songs in <strong><%=@album.name%></strong></h1>
<% @album.songs.each do |song| %>
  <%= song.titleized_title %> - <%= song.titleized_artist %> - <%= song.titleized_genres %> <br>
<% end %>

app/views/artists/new.html.erb
<h1>Create a new Artist</h1>
<%= form_for @artist do |f| %>
  Artist Name: <%= f.text_field :name %><br>

  <h2>Albums</h2>
  <%= f.fields_for :albums do |album| %>

    Album Name: <%= album.text_field :name %>

    <h4>Album Songs</h4>
    <%= album.fields_for :songs do |song| %>

      Song Title: <%= song.text_field :title %>

    <% end %>

  <% end %>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedForms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Album Index", albums_path %> - <%= link_to "Create a new Album", new_album_path %>
<hr>
<%= yield %>

</body>
</html>

app/views/songs/new.html.erb
<% form_for @album do |f| %>
  
  Album name: <%= f.text_field :name %>

  <% @songs.each do |song| %>
      <%= f.fields_for song do |s| %>
         Song Title: <%= s.text_field :title %>
         Song Artist: <%= s.text_field :artist_name %>
      <% end %>
  <% end %>

<% end %>  